name: Build A146B Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Kernel Source
        run: |
          wget https://github.com/vyasmegha91/A146B-kernel/releases/download/v1.0/Kernel.tar.gz
          tar -xzf Kernel.tar.gz

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git gcc g++ make bc \
            libssl-dev libelf-dev \
            gcc-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu python3

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make exynos1330-a14xmxx_defconfig
          make -j$(nproc)

      - name: Package Kernel
        run: |
          zip -r kernel-A146B.zip arch/arm64/boot/

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: kernel-A146B
          path: kernel-A146B.zip
